const TOTAL_RETRY_OF_COMMANDS = 3;
const MINIMUM_TEMPRATURE_ON_FAHRENHEIT = 35;
const MAXIMUM_TEMPRATURE_ON_FAHRENHEIT = 95;
const SET_POINT_TYPE_COOLING = 3;
const SET_POINT_TYPE_HEAT = 2;
const SET_POINT_TYPE_COOLING_ON_COMMAND = 1;
const SET_POINT_TYPE_HEAT_ON_COMMAND = 0;

module.exports = {
    TOTAL_RETRY_OF_COMMANDS,
    MINIMUM_TEMPRATURE_ON_FAHRENHEIT,
    MAXIMUM_TEMPRATURE_ON_FAHRENHEIT,
    SET_POINT_TYPE_COOLING,
    SET_POINT_TYPE_HEAT,
    SET_POINT_TYPE_COOLING_ON_COMMAND,
    SET_POINT_TYPE_HEAT_ON_COMMAND
}